name: final_project_vaccine
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.8
  printing: ^5.11.1
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/image/

  fonts:
    - family: VERDANAI
      fonts:
        - asset: fonts/VERDANAI.ttf
    - family: Sarabun-Regular
      fonts:
        - asset: fonts/Sarabun-Regular.ttf